### PR TITLE
fix API methods like PayPal.openIdConnect.userinfo.get()

### PR DESCRIPTION
**Pull request by rse**
fix API methods like PayPal.openIdConnect.userinfo.get() where PayPal returns an HTTP 'Content-Type' header with the value 'application/json;charset=UTF-8' instead of just 'application/json'.

### CODE REVIEW

**Comment by avidas** [comment]
Hey @rse , this looks good for a merge to me, thanks :+1:

**Comment by darrin** [comment]
Ran into this... appears to be the same issue.  Would be great to get this in a release.

**Comment by avidas** [comment]
We'll have this out as part of the next release.

**Comment by avidas** [comment]
Out in 1.5.2 release

**Pull request merged**
